import 'dart:async';
import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

import '../models/device_alert.dart';
import '../models/device_position.dart';
import '../utils/parsers.dart';

class MqttTopicDefinition {
  const MqttTopicDefinition({
    required this.topic,
    required this.description,
    this.samplePayload,
  });

  final String topic;
  final String description;
  final String? samplePayload;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'topic': topic,
      'description': description,
      'samplePayload': samplePayload,
    };
  }
}

class MqttEnvelope {
  const MqttEnvelope({
    required this.topic,
    required this.payload,
    required this.receivedAt,
    required this.isRetained,
    this.decodedPayload,
  });

  final String topic;
  final String payload;
  final DateTime receivedAt;
  final bool isRetained;
  final Object? decodedPayload;

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'topic': topic,
      'payload': payload,
      'receivedAt': receivedAt.toIso8601String(),
      'isRetained': isRetained,
      'decodedPayload': decodedPayload,
    };
  }
}

class MqttService {
  MqttService({
    required this.broker,
    required this.port,
    required this.token,
    required this.deviceId,
    this.geofenceCalcId,
    this.onPositionReceived,
    this.onAlertReceived,
    this.preferWebSocket = true,
    this.tlsFallbackPort = 8883,
    this.enableLogging = true,
  });

  final String broker;
  final int port;
  final String token;
  final String deviceId;
  final String? geofenceCalcId;
  final FutureOr<void> Function(DevicePosition position)? onPositionReceived;
  final FutureOr<void> Function(DeviceAlert alert)? onAlertReceived;
  final bool preferWebSocket;
  final int tlsFallbackPort;
  final bool enableLogging;

  final StreamController<DevicePosition> _positionController =
      StreamController<DevicePosition>.broadcast();
  final StreamController<DeviceAlert> _alertController =
      StreamController<DeviceAlert>.broadcast();
  final StreamController<MqttEnvelope> _messageController =
      StreamController<MqttEnvelope>.broadcast();
  final StreamController<int> _unseenController = StreamController<int>.broadcast();
  final Map<String, StreamController<MqttEnvelope>> _topicControllers =
      <String, StreamController<MqttEnvelope>>{};
  final Set<String> _subscribedTopics = <String>{};

  MqttServerClient? _client;
  double? _latestBatteryLevel;
  DevicePosition? _latestPosition;
  DeviceAlert? _lastGeofenceAlert;
  StreamSubscription<List<MqttReceivedMessage<MqttMessage>>>? _updatesSubscription;
  bool _isConnected = false;
  String _activeTransport = 'disconnected';

  String get _mqttUsername => token;

  String get _clientIdentifier => 'ontacoche_$deviceId';

  String get topic => 'flespi/state/gw/devices/$deviceId/telemetry/position';

  String get deviceTopicPrefix => 'flespi/state/gw/devices/$deviceId';

  String get deviceMessageTopic => 'flespi/message/gw/devices/$deviceId';

    String? get geofenceCalcActivatedTopic =>
      _hasGeofenceCalculator
        ? 'flespi/interval/gw/calcs/$geofenceCalcId/devices/$deviceId/activated'
        : null;

    bool get _hasGeofenceCalculator =>
      geofenceCalcId != null && geofenceCalcId!.trim().isNotEmpty;

  List<MqttTopicDefinition> get registeredTopics => <MqttTopicDefinition>[
    MqttTopicDefinition(
      topic: topic,
      description: 'Live device position updates parsed into DevicePosition objects.',
      samplePayload: '{"latitude":38.052348,"longitude":-1.217116,"speed":0}',
    ),
    MqttTopicDefinition(
      topic: '$deviceTopicPrefix/telemetry/#',
      description: 'Wildcard subscription for any device telemetry parameter published by flespi.',
    ),
    MqttTopicDefinition(
      topic: '$deviceTopicPrefix/#',
      description: 'Wildcard subscription for any state node exposed under the device branch.',
    ),
    MqttTopicDefinition(
      topic: deviceMessageTopic,
      description: 'Raw device messages published by flespi with all top-level parameters.',
    ),
    if (geofenceCalcActivatedTopic != null)
      MqttTopicDefinition(
        topic: geofenceCalcActivatedTopic!,
        description: 'Explicit geofence enter or exit intervals generated by the assigned calculator.',
      ),
  ];

  Stream<DevicePosition> get positions => _positionController.stream;

  Stream<DeviceAlert> get alerts => _alertController.stream;

  Stream<MqttEnvelope> get messages => _messageController.stream;

  Stream<int> get unseenCount => _unseenController.stream;

  bool get isConnected => _isConnected;

  String get activeTransport => _activeTransport;

  Future<void> connect() async {
    if (_client != null && _isConnected) {
      return;
    }

    await disconnect();
    await _closeRemoteSessionsWithSameClientId();

    final List<_MqttConnectionAttempt> attempts = _buildConnectionAttempts();
    Object? lastError;

    for (final _MqttConnectionAttempt attempt in attempts) {
      final MqttServerClient client = _buildClient(attempt);
      _client = client;

      try {
        await client.connect();
      } on Exception catch (error) {
        lastError = error;
        client.disconnect();
        _client = null;
        _isConnected = false;
        continue;
      }

      final MqttConnectionState? state = client.connectionStatus?.state;
      if (state != MqttConnectionState.connected) {
        lastError =
            'state=$state returnCode=${client.connectionStatus?.returnCode} transport=${attempt.label}';
        client.disconnect();
        _client = null;
        _isConnected = false;
        continue;
      }

      _activeTransport = attempt.label;
      _updatesSubscription?.cancel();
      _updatesSubscription = client.updates?.listen(_handleUpdates);
      for (final String subscribedTopic in _topicsToSubscribe()) {
        client.subscribe(subscribedTopic, MqttQos.atLeastOnce);
      }
      return;
    }

    _activeTransport = 'disconnected';
    throw MqttServiceException(
      'Unable to connect to Flespi MQTT after trying ${attempts.map((attempt) => attempt.label).join(', ')}. Last error: $lastError',
    );
  }

  Future<void> subscribeTopic(
    String topic, {
    MqttQos qos = MqttQos.atLeastOnce,
  }) async {
    _subscribedTopics.add(topic);
    if (_client != null && _isConnected) {
      _client!.subscribe(topic, qos);
    }
  }

  Future<void> unsubscribeTopic(String topic) async {
    _subscribedTopics.remove(topic);
    _client?.unsubscribe(topic);
  }

  Stream<MqttEnvelope> topicMessages(String topic) {
    final StreamController<MqttEnvelope> controller =
        _topicControllers.putIfAbsent(
      topic,
      () => StreamController<MqttEnvelope>.broadcast(),
    );
    return controller.stream;
  }

  MqttServerClient _buildClient(_MqttConnectionAttempt attempt) {
    if (attempt.useWebSocket) {
      // For WebSockets, we MUST NOT use withPort but standard constructor
      // and then configure useWebSocket, port and other properties.
      final MqttServerClient client = MqttServerClient(
        broker,
        _clientIdentifier,
      );
      client.port = attempt.port;
      client.useWebSocket = true;
      // Many WSS implementations require the 'mqtt' subprotocol explicitly
      client.websocketProtocols = <String>['mqtt'];
      
      client.setProtocolV311();
      client.secure = true;
      
      client.connectTimeoutPeriod = 5000;
      client.keepAlivePeriod = 30;
      client.autoReconnect = true;
      client.resubscribeOnAutoReconnect = true;
      client.onConnected = _handleConnected;
      client.onDisconnected = _handleDisconnected;
      client.onSubscribed = _handleSubscribed;
      client.logging(on: enableLogging);

      final MqttConnectMessage connectionMessage = MqttConnectMessage()
        .withClientIdentifier(_clientIdentifier)
        .withProtocolName(MqttClientConstants.mqttV311ProtocolName)
        .withProtocolVersion(MqttClientConstants.mqttV311ProtocolVersion)
        .authenticateAs(_mqttUsername, '');

      client.connectionMessage = connectionMessage;
      return client;
    } else {
      // Standard TCP TLS connection
      final MqttServerClient client = MqttServerClient.withPort(
        broker,
        _clientIdentifier,
        attempt.port,
      );
      client.setProtocolV311();
      client.secure = true;
      client.connectTimeoutPeriod = 5000;
      client.keepAlivePeriod = 30;
      client.autoReconnect = true;
      client.resubscribeOnAutoReconnect = true;
      client.onConnected = _handleConnected;
      client.onDisconnected = _handleDisconnected;
      client.onSubscribed = _handleSubscribed;
      client.logging(on: enableLogging);

      final MqttConnectMessage connectionMessage = MqttConnectMessage()
        .withClientIdentifier(_clientIdentifier)
        .withProtocolName(MqttClientConstants.mqttV311ProtocolName)
        .withProtocolVersion(MqttClientConstants.mqttV311ProtocolVersion)
        .authenticateAs(_mqttUsername, '');

      client.connectionMessage = connectionMessage;
      return client;
    }
  }

  List<_MqttConnectionAttempt> _buildConnectionAttempts() {
    final List<_MqttConnectionAttempt> attempts = <_MqttConnectionAttempt>[];

    // Favor standard TLS on 8883 as it's typically faster in non-web environments
    attempts.add(_MqttConnectionAttempt(
      port: 8883,
      useWebSocket: false,
      label: 'tls:8883',
    ));

    // Fallback to WSS on 443 if requested or TLS fails
    if (preferWebSocket || port == 443) {
      attempts.add(_MqttConnectionAttempt(
        port: 443,
        useWebSocket: true,
        label: 'wss:443',
      ));
    }

    return attempts;
  }

  Future<void> disconnect() async {
    await _updatesSubscription?.cancel();
    _updatesSubscription = null;
    _client?.disconnect();
    _client = null;
    _isConnected = false;
    _activeTransport = 'disconnected';
  }

  Future<void> _closeRemoteSessionsWithSameClientId() async {
    try {
      final Uri listUri = Uri.parse(
        'https://flespi.io/mqtt/sessions/all?fields=id,client_id,connected',
      );
      final http.Response listResponse = await http.get(
        listUri,
        headers: <String, String>{
          'Authorization': 'FlespiToken $token',
        },
      );

      if (listResponse.statusCode >= 400) {
        return;
      }

      final Object? decoded = jsonDecode(listResponse.body);
      if (decoded is! Map<String, dynamic>) {
        return;
      }

      final Object? result = decoded['result'];
      if (result is! List) {
        return;
      }

      final List<int> staleSessionIds = result
          .whereType<Map<String, dynamic>>()
          .where((Map<String, dynamic> item) => item['client_id'] == _clientIdentifier)
          .map((Map<String, dynamic> item) => item['id'])
          .whereType<num>()
          .map((num id) => id.toInt())
          .toList(growable: false);

      if (staleSessionIds.isEmpty) {
        return;
      }

      final Uri deleteUri = Uri.parse(
        'https://flespi.io/mqtt/sessions/${staleSessionIds.join(',')}',
      );
      await http.delete(
        deleteUri,
        headers: <String, String>{
          'Authorization': 'FlespiToken $token',
        },
      );
    } catch (_) {
      // ignore remote cleanup failures and still attempt a local connection
    }
  }

  void _handleConnected() {
    _isConnected = true;
  }

  void _handleDisconnected() {
    _isConnected = false;
  }

  void _handleSubscribed(String subscribedTopic) {
    if (!_topicsToSubscribe().contains(subscribedTopic)) {
      return;
    }
  }

  void _handleUpdates(List<MqttReceivedMessage<MqttMessage>> messages) {
    for (final MqttReceivedMessage<MqttMessage> message in messages) {
      final MqttPublishMessage payloadMessage = message.payload as MqttPublishMessage;
      final bool isRetained = payloadMessage.header!.retain;
      final String payload = MqttPublishPayload.bytesToStringAsString(
        payloadMessage.payload.message,
      );

      if (payload.isEmpty) {
        continue;
      }

      dynamic decodedPayload;
      try {
        decodedPayload = jsonDecode(payload);
      } catch (_) {
        decodedPayload = null;
      }

      final MqttEnvelope envelope = MqttEnvelope(
        topic: message.topic,
        payload: payload,
        receivedAt: Parsers.now(),
        isRetained: isRetained,
        decodedPayload: decodedPayload,
      );
      _messageController.add(envelope);
      _topicControllers[message.topic]?.add(envelope);

      if (message.topic.startsWith('$deviceTopicPrefix/telemetry/')) {
        final String paramKey = message.topic.substring(
          '$deviceTopicPrefix/telemetry/'.length,
        );
        if (paramKey == 'battery.level') {
          final double? level = decodedPayload is Map<String, dynamic>
              ? DevicePosition.readDouble(decodedPayload['value'])
              : DevicePosition.readDouble(decodedPayload);
          if (level != null) {
            _latestBatteryLevel = level;
            if (_latestPosition != null) {
              final DevicePosition updated = DevicePosition(
                latitude: _latestPosition!.latitude,
                longitude: _latestPosition!.longitude,
                altitude: _latestPosition!.altitude,
                speed: _latestPosition!.speed,
                timestamp: _latestPosition!.timestamp,
                batteryLevel: level,
              );
              _latestPosition = updated;
              _positionController.add(updated);
              final FutureOr<void>? persistResult = onPositionReceived?.call(updated);
              if (persistResult is Future<void>) {
                unawaited(persistResult);
              }
            }
          }
          continue;
        }

        if (paramKey == 'plugin.geofence.name' ||
            paramKey == 'plugin.geofence.status') {
          // geofence state topics are state snapshots, not edge events.
          // enter/exit notifications must come only from calculator intervals.
          continue;
        }
      }

      if (message.topic == deviceMessageTopic && decodedPayload is Map<String, dynamic>) {
        try {
          final double? batteryLevel = DevicePosition.readDouble(decodedPayload['battery.level']);
          if (batteryLevel != null) {
            _latestBatteryLevel = batteryLevel;
          }

          final List<DeviceAlert> alerts = DeviceAlert.fromDeviceMessage(
            Map<String, dynamic>.from(decodedPayload),
          );
          for (final DeviceAlert alert in alerts) {
            _alertController.add(alert);
            final FutureOr<void>? persistResult = onAlertReceived?.call(alert);
            if (persistResult is Future<void>) {
              unawaited(persistResult);
            }
          }
        } catch (_) {
          // Ignore malformed message payloads.
        }
      }

      if (geofenceCalcActivatedTopic != null &&
          message.topic == geofenceCalcActivatedTopic) {
        try {
          _handleCalculatorPayload(decodedPayload);
        } catch (_) {
          // Ignore malformed calculator payloads.
        }
      }

      if (message.topic == topic && decodedPayload is Map<String, dynamic>) {
        try {
          final Map<String, dynamic> decoded = decodedPayload;
          final DevicePosition position = DevicePosition.fromFlespiJson(decoded);

          double? batteryToUse = position.batteryLevel;
          if (batteryToUse == null && _latestBatteryLevel != null) {
            batteryToUse = _latestBatteryLevel;
          }
          if (batteryToUse == null && _latestPosition?.batteryLevel != null) {
            batteryToUse = _latestPosition!.batteryLevel;
          }

          final DevicePosition combinedPosition = DevicePosition(
            latitude: position.latitude,
            longitude: position.longitude,
            altitude: position.altitude,
            speed: position.speed,
            timestamp: position.timestamp,
            batteryLevel: batteryToUse,
          );

          _latestPosition = combinedPosition;
          _positionController.add(combinedPosition);
          final FutureOr<void>? persistResult = onPositionReceived?.call(combinedPosition);
          if (persistResult is Future<void>) {
            unawaited(persistResult);
          }
        } catch (error, stackTrace) {
          _positionController.addError(
            MqttServiceException('Unable to parse MQTT payload: $error'),
            stackTrace,
          );
        }
      }
    }
  }

  Future<void> dispose() async {
    await disconnect();
    await _positionController.close();
    await _alertController.close();
    await _messageController.close();
    await _unseenController.close();
    for (final StreamController<MqttEnvelope> controller in _topicControllers.values) {
      await controller.close();
    }
  }

  /// Called externally to update the current unseen alerts count (e.g. from DB).
  void publishUnseenCount(int count) {
    if (!_unseenController.isClosed) {
      _unseenController.add(count);
    }
  }

  Set<String> _topicsToSubscribe() {
    final Set<String> topics = <String>{
      topic,
      deviceMessageTopic,
      '$deviceTopicPrefix/telemetry/+',
      ..._subscribedTopics
    };

    if (geofenceCalcActivatedTopic != null) {
      topics.add(geofenceCalcActivatedTopic!);
    }

    return topics;
  }

  void _handleCalculatorPayload(dynamic decodedPayload) {
    if (decodedPayload is Map<String, dynamic>) {
      _emitGeofenceAlert(DeviceAlert.fromCalculatorInterval(decodedPayload));
      return;
    }

    if (decodedPayload is List) {
      for (final dynamic item in decodedPayload) {
        if (item is Map<String, dynamic>) {
          _emitGeofenceAlert(DeviceAlert.fromCalculatorInterval(item));
        }
      }
    }
  }

  void _emitGeofenceAlert(DeviceAlert? alert) {
    if (alert == null) {
      return;
    }

    final DeviceAlert? lastAlert = _lastGeofenceAlert;
    if (lastAlert != null &&
        lastAlert.isEntering == alert.isEntering &&
        lastAlert.geofenceName == alert.geofenceName &&
        alert.timestamp.difference(lastAlert.timestamp).abs() <= const Duration(seconds: 15)) {
      return;
    }

    _lastGeofenceAlert = alert;
    _alertController.add(alert);
    
    final FutureOr<void>? persistResult = onAlertReceived?.call(alert);
    if (persistResult is Future<void>) {
      unawaited(persistResult);
    }
  }
}

class MqttServiceException implements Exception {
  const MqttServiceException(this.message);

  final String message;

  @override
  String toString() => 'MqttServiceException: $message';
}

class _MqttConnectionAttempt {
  const _MqttConnectionAttempt({
    required this.port,
    required this.useWebSocket,
    required this.label,
  });

  final int port;
  final bool useWebSocket;
  final String label;
}